### ISSUE TITLE
Instructions web page not working

### ISSUE THREAD

**Issue by OfficialAhmed** [nasa/instructions#59] opened 2022-06-18 19:52 UTC
I tried to open the instructions published page didn't work **(404 - There isn't a GitHub Pages site here)**

**Comment by wbnns** [comment] 2022-08-04 09:32
@OfficialAhmed 

Hello, I did a cursory check of the links just now and did not see where there is a GitHub page that is 404'ing. Can you please paste an excerpt of the text where the link is so we can do a search for it, or provide a URL directly to it, in-line?

**Comment by OfficialAhmed** [comment] 2022-08-16 00:02
### _https://nasa.github.io/instructions_

![Screenshot 2022-08-16 040045](https://user-images.githubusercontent.com/52674147/184756171-981876d3-5ac6-4775-8d90-3d0849a24f15.jpg)

**Comment by wbnns** [comment] 2022-08-16 14:48
Thanks for the additional information. If you have additional steps that can be repeated to encounter this link, that would be helpful. In looking for this URL, I can see there is some JavaScript in `index.html` that points to this 404'd page.

Will open a PR to fix since that page has been deprecated.

**Comment by OfficialAhmed** [comment] 2023-04-05 14:57
Still doesn't work.. its 404'ing still cant open the page

**Comment by vishalsingh2972** [comment] 2023-06-21 08:58
@wbnns can you assign this to me if the issue is still open?

**Closed** 2023-07-30 06:37 UTC
